"""Regression tests for launchers generated by setup.sh."""
from __future__ import annotations

import os
from pathlib import Path
import subprocess

import pytest


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SETUP = PROJECT_ROOT / "setup.sh"


def _write_client_launcher(tmp_path: Path) -> Path:
    setup = SETUP.read_text()
    marker = 'atomic_private_write "$SCRIPT_DIR/run_client.sh" 700 << LAUNCHER\n'
    launcher = setup.split(marker, 1)[1].split("\nLAUNCHER", 1)[0].replace(r"\$", "$")
    path = tmp_path / "run_client.sh"
    path.write_text(launcher)
    path.chmod(0o700)
    (tmp_path / "venv" / "bin").mkdir(parents=True)
    (tmp_path / "venv" / "bin" / "activate").write_text("")
    return path


def _setup_helpers() -> str:
    return SETUP.read_text().split("# ── Defaults", 1)[0]


def _run_helper(command: str, destination: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["bash", "-c", f"{_setup_helpers()}\n{command}"],
        env={**os.environ, "DEST": str(destination)},
        text=True,
        capture_output=True,
    )


def test_atomic_private_write_refuses_symlink(tmp_path):
    target = tmp_path / "target"
    target.write_text("old")
    destination = tmp_path / "output"
    destination.symlink_to(target)

    result = _run_helper("printf new | atomic_private_write \"$DEST\" 600", destination)

    assert result.returncode != 0
    assert target.read_text() == "old"


def test_atomic_private_write_replaces_hardlink_without_modifying_sibling(tmp_path):
    destination = tmp_path / "output"
    destination.write_text("old")
    sibling = tmp_path / "sibling"
    os.link(destination, sibling)

    result = _run_helper("printf new | atomic_private_write \"$DEST\" 600", destination)

    assert result.returncode == 0
    assert destination.read_text() == "new"
    assert sibling.read_text() == "old"


def test_atomic_private_append_replaces_hardlink_without_modifying_sibling(tmp_path):
    destination = tmp_path / "output"
    destination.write_text("old")
    sibling = tmp_path / "sibling"
    os.link(destination, sibling)

    result = _run_helper("printf new | atomic_private_append \"$DEST\" 600", destination)

    assert result.returncode == 0
    assert destination.read_text() == "oldnew"
    assert sibling.read_text() == "old"


def test_atomic_private_append_refuses_symlink(tmp_path):
    target = tmp_path / "target"
    target.write_text("old")
    destination = tmp_path / "output"
    destination.symlink_to(target)

    result = _run_helper("printf new | atomic_private_append \"$DEST\" 600", destination)

    assert result.returncode != 0
    assert target.read_text() == "old"


def test_systemd_escape_path_escapes_spaces_and_percents(tmp_path):
    destination = tmp_path / "before space%done"

    result = _run_helper('systemd_escape_path "$DEST"', destination)

    expected = (
        str(destination)
        .replace(" ", r"\x20")
        .replace("%", "%%")
    )
    assert result.returncode == 0
    assert result.stdout == expected


@pytest.mark.parametrize("name", ['before"after', "before\\after", "before\nafter"])
def test_systemd_escape_path_rejects_unsupported_characters(tmp_path, name):
    result = _run_helper('systemd_escape_path "$DEST"', tmp_path / name)

    assert result.returncode != 0
    assert "Cannot write systemd service" in result.stdout


def test_config_value_is_safe_accepts_serial_path(tmp_path):
    result = _run_helper('config_value_is_safe "$DEST"', tmp_path / "ttyUSB0")

    assert result.returncode == 0


@pytest.mark.parametrize("name", ["before\nafter", "before\rafter", "before\x1bafter"])
def test_config_value_is_safe_rejects_control_characters(tmp_path, name):
    result = _run_helper('config_value_is_safe "$DEST"', tmp_path / name)

    assert result.returncode != 0


def test_rnode_environment_port_is_validated_before_rendering():
    setup = SETUP.read_text()

    assert setup.index('! config_value_is_safe "$RNODE_PORT"') < setup.index("Using RNode serial device")


def test_rnode_selected_port_is_validated_before_config_append():
    setup = SETUP.read_text()

    assert setup.rindex('! config_value_is_safe "$RNODE_PORT"') > setup.index('RNODE_PORT="$manual_port"')
    assert setup.rindex('! config_value_is_safe "$RNODE_PORT"') < setup.index('port              = ${RNODE_PORT}')


def test_setup_inline_python_receives_filesystem_paths_through_env():
    setup = SETUP.read_text()

    assert 'ANONMESH_RNS_CONFIG_FILE="$RNS_CONFIG_FILE" python -c' in setup
    assert 'open(os.environ["ANONMESH_RNS_CONFIG_FILE"])' in setup
    assert 'ANONMESH_SCRIPT_DIR="$SCRIPT_DIR" python -c' in setup
    assert 'sys.path.insert(0, os.environ["ANONMESH_SCRIPT_DIR"])' in setup
    assert "open('$RNS_CONFIG_FILE')" not in setup
    assert "sys.path.insert(0, '$SCRIPT_DIR')" not in setup


def test_client_launcher_preserves_hex_looking_option_value(tmp_path):
    launcher = _write_client_launcher(tmp_path)
    capture = tmp_path / "args"
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    fake_python = bin_dir / "python"
    fake_python.write_text(
        "#!/usr/bin/env bash\n"
        "printf '%s\\n' \"$@\" > \"$ANONMESH_CAPTURE\"\n"
    )
    fake_python.chmod(0o700)
    beacon_hash = "a" * 32
    transaction = "b" * 64

    subprocess.run(
        [str(launcher), beacon_hash, "--send-tx", transaction],
        check=True,
        env={
            **os.environ,
            "ANONMESH_CAPTURE": str(capture),
            "PATH": f"{bin_dir}:{os.environ['PATH']}",
        },
    )

    assert capture.read_text().splitlines() == [
        str(tmp_path / "client.py"),
        "--beacon",
        beacon_hash,
        "--discover",
        "--strategy",
        "race",
        "--send-tx",
        transaction,
    ]
