"""Regression tests for launchers generated by setup.sh."""
from __future__ import annotations

import os
from pathlib import Path
import subprocess


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SETUP = PROJECT_ROOT / "setup.sh"


def _write_client_launcher(tmp_path: Path) -> Path:
    setup = SETUP.read_text()
    marker = 'cat > "$SCRIPT_DIR/run_client.sh" << LAUNCHER\n'
    launcher = setup.split(marker, 1)[1].split("\nLAUNCHER", 1)[0].replace(r"\$", "$")
    path = tmp_path / "run_client.sh"
    path.write_text(launcher)
    path.chmod(0o700)
    (tmp_path / "venv" / "bin").mkdir(parents=True)
    (tmp_path / "venv" / "bin" / "activate").write_text("")
    return path


def test_client_launcher_preserves_hex_looking_option_value(tmp_path):
    launcher = _write_client_launcher(tmp_path)
    capture = tmp_path / "args"
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    fake_python = bin_dir / "python"
    fake_python.write_text(
        "#!/usr/bin/env bash\n"
        "printf '%s\\n' \"$@\" > \"$ANONMESH_CAPTURE\"\n"
    )
    fake_python.chmod(0o700)
    beacon_hash = "a" * 32
    transaction = "b" * 64

    subprocess.run(
        [str(launcher), beacon_hash, "--send-tx", transaction],
        check=True,
        env={
            **os.environ,
            "ANONMESH_CAPTURE": str(capture),
            "PATH": f"{bin_dir}:{os.environ['PATH']}",
        },
    )

    assert capture.read_text().splitlines() == [
        str(tmp_path / "client.py"),
        "--beacon",
        beacon_hash,
        "--discover",
        "--strategy",
        "race",
        "--send-tx",
        transaction,
    ]
